version: "3.8"
services:
  api:
    build:
      context: .
      target: build
    networks:
      - task-mgmt-service-network
    volumes:
      - .:/app
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    environment:
      - DB_CONNECTION_URL=mongodb://mongodb:27017/appName=dbdata
    command: npm run dev

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - task-mgmt-service-network

volumes:
  dbdata:

networks:
  task-mgmt-service-network:
    driver: bridge
